services:
  http-wakeonlan:
    build: .
    container_name: http-wakeonlan
    network_mode: host
    environment:
      AUTH_KEY: "super-secret-token"
      TARGET_MAC: "AA:BB:CC:DD:EE:FF"
      WOL_DESTINATION_IP: "255.255.255.255"
      WOL_PORT: "9"
      RESPONSE_MESSAGE: "Wake-on-LAN packet sent"
      HOST: "0.0.0.0"
      PORT: "8080"
    restart: unless-stopped
